# This file is part of the CampaignChain package.
#
# (c) CampaignChain, Inc. <info@campaignchain.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

campaignchain_milestone_scheduled_new:
    pattern:  /milestone/scheduled/new/{campaign}
    defaults: { _controller: CampaignChainMilestoneScheduledMilestoneBundle:ScheduledMilestone:new }

campaignchain_milestone_scheduled_edit:
    pattern:  /milestone/scheduled/{id}/edit
    defaults: { _controller: CampaignChainMilestoneScheduledMilestoneBundle:ScheduledMilestone:edit }

campaignchain_milestone_scheduled_edit_modal:
    pattern:  /modal/milestone/scheduled/{id}/edit
    defaults: { _controller: CampaignChainMilestoneScheduledMilestoneBundle:ScheduledMilestone:editModal }

campaignchain_milestone_scheduled_edit_api:
    pattern:  /api/private/milestone/scheduled/{id}/edit
    defaults: { _controller: CampaignChainMilestoneScheduledMilestoneBundle:ScheduledMilestone:editApi }
    options:
        expose: true